services:
  frontend:
    #build:
    # context: .
    # dockerfile: Dockerfile
    image: trungnghia1996/nuxt4-template:latest
    container_name: vn_time_table
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      NUXT_PUBLIC_BASE_URL: https://api.nghia196.io.vn
      NUXT_ENCRYPTION_KEY: key-32-chars-123456
    ports:
      - "3000:3000"
